/**
 * Auto-generated Device Specifications - MINIMAL VERSION
 * Generated manually for immediate fix
 * 
 * DO NOT EDIT THIS FILE MANUALLY
 * Full regeneration needed from device packs
 */
// PIC12 Family
static constexpr DeviceSpec PIC10F200_SPEC{
    "PIC10F200",
    512,      // program memory (256 words * 2 bytes/word)
    24,       // data memory (RAM)
    0,        // EEPROM
    Architecture::PIC12
};
// PIC16 Family  
static constexpr DeviceSpec PIC16F15313_SPEC{
    "PIC16F15313",
    3584,     // program memory (1792 words * 2 bytes/word = 3.5KB)
    256,      // data memory (RAM)
    0,        // EEPROM
    Architecture::PIC16
};
static constexpr DeviceSpec PIC16F15323_SPEC{
    "PIC16F15323",
    3584,     // program memory (1792 words * 2 bytes/word = 3.5KB)
    256,      // data memory (RAM)
    0,        // EEPROM
    Architecture::PIC16
};
static constexpr DeviceSpec PIC16F1847_SPEC{
    "PIC16F1847",
    16384,    // program memory (8192 words * 2 bytes/word)
    1024,     // data memory (RAM)
    256,      // EEPROM
    Architecture::PIC16
};
// PIC18 Family
static constexpr DeviceSpec PIC18F06Q40_SPEC{
    "PIC18F06Q40",
    32768,    // program memory (16384 words * 2 bytes/word)
    2048,     // data memory (RAM)
    256,      // EEPROM
    Architecture::PIC18
};
