/**
 * Auto-generated Device Specifications
 * Generated from: device_memory_specs.txt
 * 
 * DO NOT EDIT THIS FILE MANUALLY
 * Edit device_memory_specs.txt and regenerate using generate_device_specs tool
 */

#pragma once

    static constexpr DeviceSpec PIC10F200_SPEC{
        "PIC10F200",
        512,      // program memory (256 words * 2 bytes/word)
        16,       // data memory (RAM)
        0,     // EEPROM
        Architecture::PIC12
    };

    static constexpr DeviceSpec PIC10F202_SPEC{
        "PIC10F202",
        1024,      // program memory (512 words * 2 bytes/word)
        24,       // data memory (RAM)
        0,     // EEPROM
        Architecture::PIC12
    };

    static constexpr DeviceSpec PIC10F204_SPEC{
        "PIC10F204",
        512,      // program memory (256 words * 2 bytes/word)
        16,       // data memory (RAM)
        0,     // EEPROM
        Architecture::PIC12
    };

    static constexpr DeviceSpec PIC10F206_SPEC{
        "PIC10F206",
        1024,      // program memory (512 words * 2 bytes/word)
        24,       // data memory (RAM)
        0,     // EEPROM
        Architecture::PIC12
    };

    static constexpr DeviceSpec PIC10F220_SPEC{
        "PIC10F220",
        512,      // program memory (256 words * 2 bytes/word)
        16,       // data memory (RAM)
        0,     // EEPROM
        Architecture::PIC12
    };

    static constexpr DeviceSpec PIC10F222_SPEC{
        "PIC10F222",
        1024,      // program memory (512 words * 2 bytes/word)
        24,       // data memory (RAM)
        0,     // EEPROM
        Architecture::PIC12
    };

    static constexpr DeviceSpec PIC10F320_SPEC{
        "PIC10F320",
        512,      // program memory (256 words * 2 bytes/word)
        64,       // data memory (RAM)
        0,     // EEPROM
        Architecture::PIC12
    };

    static constexpr DeviceSpec PIC10F322_SPEC{
        "PIC10F322",
        1024,      // program memory (512 words * 2 bytes/word)
        64,       // data memory (RAM)
        0,     // EEPROM
        Architecture::PIC12
    };

    static constexpr DeviceSpec PIC12F508_SPEC{
        "PIC12F508",
        1024,      // program memory (512 words * 2 bytes/word)
        25,       // data memory (RAM)
        0,     // EEPROM
        Architecture::PIC12
    };

    static constexpr DeviceSpec PIC12F509_SPEC{
        "PIC12F509",
        2048,      // program memory (1024 words * 2 bytes/word)
        41,       // data memory (RAM)
        0,     // EEPROM
        Architecture::PIC12
    };

    static constexpr DeviceSpec PIC12F510_SPEC{
        "PIC12F510",
        1024,      // program memory (512 words * 2 bytes/word)
        25,       // data memory (RAM)
        0,     // EEPROM
        Architecture::PIC12
    };

    static constexpr DeviceSpec PIC12F519_SPEC{
        "PIC12F519",
        2048,      // program memory (1024 words * 2 bytes/word)
        41,       // data memory (RAM)
        0,     // EEPROM
        Architecture::PIC12
    };

    static constexpr DeviceSpec PIC12F609_SPEC{
        "PIC12F609",
        2048,      // program memory (1024 words * 2 bytes/word)
        64,       // data memory (RAM)
        0,     // EEPROM
        Architecture::PIC12
    };

    static constexpr DeviceSpec PIC12F615_SPEC{
        "PIC12F615",
        2048,      // program memory (1024 words * 2 bytes/word)
        64,       // data memory (RAM)
        128,     // EEPROM
        Architecture::PIC12
    };

    static constexpr DeviceSpec PIC12F617_SPEC{
        "PIC12F617",
        4096,      // program memory (2048 words * 2 bytes/word)
        128,       // data memory (RAM)
        128,     // EEPROM
        Architecture::PIC12
    };

    static constexpr DeviceSpec PIC12F629_SPEC{
        "PIC12F629",
        2048,      // program memory (1024 words * 2 bytes/word)
        64,       // data memory (RAM)
        128,     // EEPROM
        Architecture::PIC12
    };

    static constexpr DeviceSpec PIC12F635_SPEC{
        "PIC12F635",
        2048,      // program memory (1024 words * 2 bytes/word)
        64,       // data memory (RAM)
        128,     // EEPROM
        Architecture::PIC12
    };

    static constexpr DeviceSpec PIC12F675_SPEC{
        "PIC12F675",
        2048,      // program memory (1024 words * 2 bytes/word)
        64,       // data memory (RAM)
        128,     // EEPROM
        Architecture::PIC12
    };

    static constexpr DeviceSpec PIC12F683_SPEC{
        "PIC12F683",
        4096,      // program memory (2048 words * 2 bytes/word)
        128,       // data memory (RAM)
        256,     // EEPROM
        Architecture::PIC12
    };

    static constexpr DeviceSpec PIC12F752_SPEC{
        "PIC12F752",
        4096,      // program memory (2048 words * 2 bytes/word)
        128,       // data memory (RAM)
        0,     // EEPROM
        Architecture::PIC12
    };

    static constexpr DeviceSpec PIC12F1501_SPEC{
        "PIC12F1501",
        2048,      // program memory (1024 words * 2 bytes/word)
        64,       // data memory (RAM)
        0,     // EEPROM
        Architecture::PIC12
    };

    static constexpr DeviceSpec PIC12F1571_SPEC{
        "PIC12F1571",
        2048,      // program memory (1024 words * 2 bytes/word)
        64,       // data memory (RAM)
        0,     // EEPROM
        Architecture::PIC12
    };

    static constexpr DeviceSpec PIC12F1572_SPEC{
        "PIC12F1572",
        4096,      // program memory (2048 words * 2 bytes/word)
        128,       // data memory (RAM)
        0,     // EEPROM
        Architecture::PIC12
    };

    static constexpr DeviceSpec PIC12F1612_SPEC{
        "PIC12F1612",
        4096,      // program memory (2048 words * 2 bytes/word)
        128,       // data memory (RAM)
        0,     // EEPROM
        Architecture::PIC12
    };

    static constexpr DeviceSpec PIC12F1822_SPEC{
        "PIC12F1822",
        4096,      // program memory (2048 words * 2 bytes/word)
        128,       // data memory (RAM)
        256,     // EEPROM
        Architecture::PIC12
    };

    static constexpr DeviceSpec PIC12F1840_SPEC{
        "PIC12F1840",
        8192,      // program memory (4096 words * 2 bytes/word)
        256,       // data memory (RAM)
        256,     // EEPROM
        Architecture::PIC12
    };

    static constexpr DeviceSpec PIC16F84A_SPEC{
        "PIC16F84A",
        2048,      // program memory (1024 words * 2 bytes/word)
        68,       // data memory (RAM)
        64,     // EEPROM
        Architecture::PIC16
    };

    static constexpr DeviceSpec PIC16F88_SPEC{
        "PIC16F88",
        8192,      // program memory (4096 words * 2 bytes/word)
        368,       // data memory (RAM)
        256,     // EEPROM
        Architecture::PIC16
    };

    static constexpr DeviceSpec PIC16F628A_SPEC{
        "PIC16F628A",
        4096,      // program memory (2048 words * 2 bytes/word)
        224,       // data memory (RAM)
        128,     // EEPROM
        Architecture::PIC16
    };

    static constexpr DeviceSpec PIC16F648A_SPEC{
        "PIC16F648A",
        8192,      // program memory (4096 words * 2 bytes/word)
        256,       // data memory (RAM)
        256,     // EEPROM
        Architecture::PIC16
    };

    static constexpr DeviceSpec PIC16F676_SPEC{
        "PIC16F676",
        2048,      // program memory (1024 words * 2 bytes/word)
        64,       // data memory (RAM)
        128,     // EEPROM
        Architecture::PIC16
    };

    static constexpr DeviceSpec PIC16F684_SPEC{
        "PIC16F684",
        4096,      // program memory (2048 words * 2 bytes/word)
        128,       // data memory (RAM)
        256,     // EEPROM
        Architecture::PIC16
    };

    static constexpr DeviceSpec PIC16F687_SPEC{
        "PIC16F687",
        4096,      // program memory (2048 words * 2 bytes/word)
        128,       // data memory (RAM)
        256,     // EEPROM
        Architecture::PIC16
    };

    static constexpr DeviceSpec PIC16F688_SPEC{
        "PIC16F688",
        8192,      // program memory (4096 words * 2 bytes/word)
        256,       // data memory (RAM)
        256,     // EEPROM
        Architecture::PIC16
    };

    static constexpr DeviceSpec PIC16F689_SPEC{
        "PIC16F689",
        8192,      // program memory (4096 words * 2 bytes/word)
        256,       // data memory (RAM)
        256,     // EEPROM
        Architecture::PIC16
    };

    static constexpr DeviceSpec PIC16F690_SPEC{
        "PIC16F690",
        8192,      // program memory (4096 words * 2 bytes/word)
        256,       // data memory (RAM)
        256,     // EEPROM
        Architecture::PIC16
    };

    static constexpr DeviceSpec PIC16F716_SPEC{
        "PIC16F716",
        4096,      // program memory (2048 words * 2 bytes/word)
        128,       // data memory (RAM)
        256,     // EEPROM
        Architecture::PIC16
    };

    static constexpr DeviceSpec PIC16F72_SPEC{
        "PIC16F72",
        4096,      // program memory (2048 words * 2 bytes/word)
        128,       // data memory (RAM)
        0,     // EEPROM
        Architecture::PIC16
    };

    static constexpr DeviceSpec PIC16F73_SPEC{
        "PIC16F73",
        8192,      // program memory (4096 words * 2 bytes/word)
        192,       // data memory (RAM)
        0,     // EEPROM
        Architecture::PIC16
    };

    static constexpr DeviceSpec PIC16F74_SPEC{
        "PIC16F74",
        8192,      // program memory (4096 words * 2 bytes/word)
        192,       // data memory (RAM)
        0,     // EEPROM
        Architecture::PIC16
    };

    static constexpr DeviceSpec PIC16F76_SPEC{
        "PIC16F76",
        16384,      // program memory (8192 words * 2 bytes/word)
        368,       // data memory (RAM)
        0,     // EEPROM
        Architecture::PIC16
    };

    static constexpr DeviceSpec PIC16F77_SPEC{
        "PIC16F77",
        16384,      // program memory (8192 words * 2 bytes/word)
        368,       // data memory (RAM)
        0,     // EEPROM
        Architecture::PIC16
    };

    static constexpr DeviceSpec PIC16F777_SPEC{
        "PIC16F777",
        16384,      // program memory (8192 words * 2 bytes/word)
        512,       // data memory (RAM)
        256,     // EEPROM
        Architecture::PIC16
    };

    static constexpr DeviceSpec PIC16F818_SPEC{
        "PIC16F818",
        2048,      // program memory (1024 words * 2 bytes/word)
        128,       // data memory (RAM)
        128,     // EEPROM
        Architecture::PIC16
    };

    static constexpr DeviceSpec PIC16F819_SPEC{
        "PIC16F819",
        4096,      // program memory (2048 words * 2 bytes/word)
        256,       // data memory (RAM)
        256,     // EEPROM
        Architecture::PIC16
    };

    static constexpr DeviceSpec PIC16F870_SPEC{
        "PIC16F870",
        4096,      // program memory (2048 words * 2 bytes/word)
        128,       // data memory (RAM)
        64,     // EEPROM
        Architecture::PIC16
    };

    static constexpr DeviceSpec PIC16F871_SPEC{
        "PIC16F871",
        4096,      // program memory (2048 words * 2 bytes/word)
        128,       // data memory (RAM)
        64,     // EEPROM
        Architecture::PIC16
    };

    static constexpr DeviceSpec PIC16F872_SPEC{
        "PIC16F872",
        4096,      // program memory (2048 words * 2 bytes/word)
        128,       // data memory (RAM)
        64,     // EEPROM
        Architecture::PIC16
    };

    static constexpr DeviceSpec PIC16F873_SPEC{
        "PIC16F873",
        8192,      // program memory (4096 words * 2 bytes/word)
        192,       // data memory (RAM)
        128,     // EEPROM
        Architecture::PIC16
    };

    static constexpr DeviceSpec PIC16F873A_SPEC{
        "PIC16F873A",
        8192,      // program memory (4096 words * 2 bytes/word)
        192,       // data memory (RAM)
        128,     // EEPROM
        Architecture::PIC16
    };

    static constexpr DeviceSpec PIC16F874_SPEC{
        "PIC16F874",
        8192,      // program memory (4096 words * 2 bytes/word)
        192,       // data memory (RAM)
        128,     // EEPROM
        Architecture::PIC16
    };

    static constexpr DeviceSpec PIC16F874A_SPEC{
        "PIC16F874A",
        8192,      // program memory (4096 words * 2 bytes/word)
        192,       // data memory (RAM)
        128,     // EEPROM
        Architecture::PIC16
    };

    static constexpr DeviceSpec PIC16F876_SPEC{
        "PIC16F876",
        16384,      // program memory (8192 words * 2 bytes/word)
        368,       // data memory (RAM)
        256,     // EEPROM
        Architecture::PIC16
    };

    static constexpr DeviceSpec PIC16F876A_SPEC{
        "PIC16F876A",
        16384,      // program memory (8192 words * 2 bytes/word)
        368,       // data memory (RAM)
        256,     // EEPROM
        Architecture::PIC16
    };

    static constexpr DeviceSpec PIC16F877_SPEC{
        "PIC16F877",
        16384,      // program memory (8192 words * 2 bytes/word)
        368,       // data memory (RAM)
        256,     // EEPROM
        Architecture::PIC16
    };

    static constexpr DeviceSpec PIC16F877A_SPEC{
        "PIC16F877A",
        16384,      // program memory (8192 words * 2 bytes/word)
        368,       // data memory (RAM)
        256,     // EEPROM
        Architecture::PIC16
    };

    static constexpr DeviceSpec PIC16F882_SPEC{
        "PIC16F882",
        4096,      // program memory (2048 words * 2 bytes/word)
        128,       // data memory (RAM)
        256,     // EEPROM
        Architecture::PIC16
    };

    static constexpr DeviceSpec PIC16F883_SPEC{
        "PIC16F883",
        8192,      // program memory (4096 words * 2 bytes/word)
        256,       // data memory (RAM)
        256,     // EEPROM
        Architecture::PIC16
    };

    static constexpr DeviceSpec PIC16F884_SPEC{
        "PIC16F884",
        8192,      // program memory (4096 words * 2 bytes/word)
        256,       // data memory (RAM)
        256,     // EEPROM
        Architecture::PIC16
    };

    static constexpr DeviceSpec PIC16F886_SPEC{
        "PIC16F886",
        16384,      // program memory (8192 words * 2 bytes/word)
        368,       // data memory (RAM)
        256,     // EEPROM
        Architecture::PIC16
    };

    static constexpr DeviceSpec PIC16F887_SPEC{
        "PIC16F887",
        16384,      // program memory (8192 words * 2 bytes/word)
        368,       // data memory (RAM)
        256,     // EEPROM
        Architecture::PIC16
    };

    static constexpr DeviceSpec PIC16F913_SPEC{
        "PIC16F913",
        8192,      // program memory (4096 words * 2 bytes/word)
        256,       // data memory (RAM)
        256,     // EEPROM
        Architecture::PIC16
    };

    static constexpr DeviceSpec PIC16F914_SPEC{
        "PIC16F914",
        8192,      // program memory (4096 words * 2 bytes/word)
        256,       // data memory (RAM)
        256,     // EEPROM
        Architecture::PIC16
    };

    static constexpr DeviceSpec PIC16F916_SPEC{
        "PIC16F916",
        16384,      // program memory (8192 words * 2 bytes/word)
        368,       // data memory (RAM)
        256,     // EEPROM
        Architecture::PIC16
    };

    static constexpr DeviceSpec PIC16F917_SPEC{
        "PIC16F917",
        16384,      // program memory (8192 words * 2 bytes/word)
        368,       // data memory (RAM)
        256,     // EEPROM
        Architecture::PIC16
    };

    static constexpr DeviceSpec PIC16F946_SPEC{
        "PIC16F946",
        16384,      // program memory (8192 words * 2 bytes/word)
        512,       // data memory (RAM)
        256,     // EEPROM
        Architecture::PIC16
    };

    static constexpr DeviceSpec PIC16F1454_SPEC{
        "PIC16F1454",
        16384,      // program memory (8192 words * 2 bytes/word)
        1024,       // data memory (RAM)
        0,     // EEPROM
        Architecture::PIC16
    };

    static constexpr DeviceSpec PIC16F1455_SPEC{
        "PIC16F1455",
        16384,      // program memory (8192 words * 2 bytes/word)
        1024,       // data memory (RAM)
        0,     // EEPROM
        Architecture::PIC16
    };

    static constexpr DeviceSpec PIC16F1459_SPEC{
        "PIC16F1459",
        16384,      // program memory (8192 words * 2 bytes/word)
        1024,       // data memory (RAM)
        0,     // EEPROM
        Architecture::PIC16
    };

    static constexpr DeviceSpec PIC16F1503_SPEC{
        "PIC16F1503",
        4096,      // program memory (2048 words * 2 bytes/word)
        128,       // data memory (RAM)
        0,     // EEPROM
        Architecture::PIC16
    };

    static constexpr DeviceSpec PIC16F1507_SPEC{
        "PIC16F1507",
        4096,      // program memory (2048 words * 2 bytes/word)
        128,       // data memory (RAM)
        0,     // EEPROM
        Architecture::PIC16
    };

    static constexpr DeviceSpec PIC16F1508_SPEC{
        "PIC16F1508",
        8192,      // program memory (4096 words * 2 bytes/word)
        256,       // data memory (RAM)
        0,     // EEPROM
        Architecture::PIC16
    };

    static constexpr DeviceSpec PIC16F1509_SPEC{
        "PIC16F1509",
        16384,      // program memory (8192 words * 2 bytes/word)
        1024,       // data memory (RAM)
        0,     // EEPROM
        Architecture::PIC16
    };

    static constexpr DeviceSpec PIC16F1512_SPEC{
        "PIC16F1512",
        4096,      // program memory (2048 words * 2 bytes/word)
        128,       // data memory (RAM)
        0,     // EEPROM
        Architecture::PIC16
    };

    static constexpr DeviceSpec PIC16F1513_SPEC{
        "PIC16F1513",
        8192,      // program memory (4096 words * 2 bytes/word)
        256,       // data memory (RAM)
        0,     // EEPROM
        Architecture::PIC16
    };

    static constexpr DeviceSpec PIC16F1516_SPEC{
        "PIC16F1516",
        16384,      // program memory (8192 words * 2 bytes/word)
        1024,       // data memory (RAM)
        0,     // EEPROM
        Architecture::PIC16
    };

    static constexpr DeviceSpec PIC16F1517_SPEC{
        "PIC16F1517",
        16384,      // program memory (8192 words * 2 bytes/word)
        1024,       // data memory (RAM)
        0,     // EEPROM
        Architecture::PIC16
    };

    static constexpr DeviceSpec PIC16F1518_SPEC{
        "PIC16F1518",
        32768,      // program memory (16384 words * 2 bytes/word)
        1520,       // data memory (RAM)
        256,     // EEPROM
        Architecture::PIC16
    };

    static constexpr DeviceSpec PIC16F1519_SPEC{
        "PIC16F1519",
        32768,      // program memory (16384 words * 2 bytes/word)
        1520,       // data memory (RAM)
        256,     // EEPROM
        Architecture::PIC16
    };

    static constexpr DeviceSpec PIC16F1526_SPEC{
        "PIC16F1526",
        16384,      // program memory (8192 words * 2 bytes/word)
        1024,       // data memory (RAM)
        0,     // EEPROM
        Architecture::PIC16
    };

    static constexpr DeviceSpec PIC16F1527_SPEC{
        "PIC16F1527",
        16384,      // program memory (8192 words * 2 bytes/word)
        1024,       // data memory (RAM)
        0,     // EEPROM
        Architecture::PIC16
    };

    static constexpr DeviceSpec PIC16F1613_SPEC{
        "PIC16F1613",
        4096,      // program memory (2048 words * 2 bytes/word)
        128,       // data memory (RAM)
        0,     // EEPROM
        Architecture::PIC16
    };

    static constexpr DeviceSpec PIC16F1614_SPEC{
        "PIC16F1614",
        8192,      // program memory (4096 words * 2 bytes/word)
        512,       // data memory (RAM)
        0,     // EEPROM
        Architecture::PIC16
    };

    static constexpr DeviceSpec PIC16F1615_SPEC{
        "PIC16F1615",
        16384,      // program memory (8192 words * 2 bytes/word)
        1024,       // data memory (RAM)
        0,     // EEPROM
        Architecture::PIC16
    };

    static constexpr DeviceSpec PIC16F1618_SPEC{
        "PIC16F1618",
        32768,      // program memory (16384 words * 2 bytes/word)
        2048,       // data memory (RAM)
        256,     // EEPROM
        Architecture::PIC16
    };

    static constexpr DeviceSpec PIC16F1619_SPEC{
        "PIC16F1619",
        32768,      // program memory (16384 words * 2 bytes/word)
        2048,       // data memory (RAM)
        256,     // EEPROM
        Architecture::PIC16
    };

    static constexpr DeviceSpec PIC16F15313_SPEC{
        "PIC16F15313",
        3584,      // program memory (1792 words * 2 bytes/word)
        256,       // data memory (RAM)
        256,     // EEPROM
        Architecture::PIC16
    };

    static constexpr DeviceSpec PIC16F15323_SPEC{
        "PIC16F15323",
        3584,      // program memory (1792 words * 2 bytes/word)
        256,       // data memory (RAM)
        256,     // EEPROM
        Architecture::PIC16
    };

    static constexpr DeviceSpec PIC16F15324_SPEC{
        "PIC16F15324",
        4096,      // program memory (2048 words * 2 bytes/word)
        512,       // data memory (RAM)
        0,     // EEPROM
        Architecture::PIC16
    };

    static constexpr DeviceSpec PIC16F15325_SPEC{
        "PIC16F15325",
        8192,      // program memory (4096 words * 2 bytes/word)
        512,       // data memory (RAM)
        0,     // EEPROM
        Architecture::PIC16
    };

    static constexpr DeviceSpec PIC16F15344_SPEC{
        "PIC16F15344",
        8192,      // program memory (4096 words * 2 bytes/word)
        1024,       // data memory (RAM)
        256,     // EEPROM
        Architecture::PIC16
    };

    static constexpr DeviceSpec PIC16F15345_SPEC{
        "PIC16F15345",
        16384,      // program memory (8192 words * 2 bytes/word)
        1024,       // data memory (RAM)
        256,     // EEPROM
        Architecture::PIC16
    };

    static constexpr DeviceSpec PIC16F15354_SPEC{
        "PIC16F15354",
        16384,      // program memory (8192 words * 2 bytes/word)
        1024,       // data memory (RAM)
        256,     // EEPROM
        Architecture::PIC16
    };

    static constexpr DeviceSpec PIC16F15355_SPEC{
        "PIC16F15355",
        32768,      // program memory (16384 words * 2 bytes/word)
        2048,       // data memory (RAM)
        256,     // EEPROM
        Architecture::PIC16
    };

    static constexpr DeviceSpec PIC16F15356_SPEC{
        "PIC16F15356",
        32768,      // program memory (16384 words * 2 bytes/word)
        2048,       // data memory (RAM)
        256,     // EEPROM
        Architecture::PIC16
    };

    static constexpr DeviceSpec PIC16F15375_SPEC{
        "PIC16F15375",
        32768,      // program memory (16384 words * 2 bytes/word)
        2048,       // data memory (RAM)
        256,     // EEPROM
        Architecture::PIC16
    };

    static constexpr DeviceSpec PIC16F15376_SPEC{
        "PIC16F15376",
        65536,      // program memory (32768 words * 2 bytes/word)
        4096,       // data memory (RAM)
        256,     // EEPROM
        Architecture::PIC16
    };

    static constexpr DeviceSpec PIC16F15385_SPEC{
        "PIC16F15385",
        32768,      // program memory (16384 words * 2 bytes/word)
        2048,       // data memory (RAM)
        256,     // EEPROM
        Architecture::PIC16
    };

    static constexpr DeviceSpec PIC16F15386_SPEC{
        "PIC16F15386",
        65536,      // program memory (32768 words * 2 bytes/word)
        4096,       // data memory (RAM)
        256,     // EEPROM
        Architecture::PIC16
    };

    static constexpr DeviceSpec PIC16F1705_SPEC{
        "PIC16F1705",
        16384,      // program memory (8192 words * 2 bytes/word)
        1024,       // data memory (RAM)
        0,     // EEPROM
        Architecture::PIC16
    };

    static constexpr DeviceSpec PIC16F1707_SPEC{
        "PIC16F1707",
        16384,      // program memory (8192 words * 2 bytes/word)
        1024,       // data memory (RAM)
        0,     // EEPROM
        Architecture::PIC16
    };

    static constexpr DeviceSpec PIC16F1708_SPEC{
        "PIC16F1708",
        8192,      // program memory (4096 words * 2 bytes/word)
        256,       // data memory (RAM)
        0,     // EEPROM
        Architecture::PIC16
    };

    static constexpr DeviceSpec PIC16F1709_SPEC{
        "PIC16F1709",
        16384,      // program memory (8192 words * 2 bytes/word)
        1024,       // data memory (RAM)
        0,     // EEPROM
        Architecture::PIC16
    };

    static constexpr DeviceSpec PIC16F1713_SPEC{
        "PIC16F1713",
        8192,      // program memory (4096 words * 2 bytes/word)
        256,       // data memory (RAM)
        0,     // EEPROM
        Architecture::PIC16
    };

    static constexpr DeviceSpec PIC16F1716_SPEC{
        "PIC16F1716",
        16384,      // program memory (8192 words * 2 bytes/word)
        1024,       // data memory (RAM)
        0,     // EEPROM
        Architecture::PIC16
    };

    static constexpr DeviceSpec PIC16F1717_SPEC{
        "PIC16F1717",
        16384,      // program memory (8192 words * 2 bytes/word)
        1024,       // data memory (RAM)
        0,     // EEPROM
        Architecture::PIC16
    };

    static constexpr DeviceSpec PIC16F1718_SPEC{
        "PIC16F1718",
        32768,      // program memory (16384 words * 2 bytes/word)
        2048,       // data memory (RAM)
        256,     // EEPROM
        Architecture::PIC16
    };

    static constexpr DeviceSpec PIC16F1719_SPEC{
        "PIC16F1719",
        32768,      // program memory (16384 words * 2 bytes/word)
        2048,       // data memory (RAM)
        256,     // EEPROM
        Architecture::PIC16
    };

    static constexpr DeviceSpec PIC16F1764_SPEC{
        "PIC16F1764",
        8192,      // program memory (4096 words * 2 bytes/word)
        512,       // data memory (RAM)
        0,     // EEPROM
        Architecture::PIC16
    };

    static constexpr DeviceSpec PIC16F1765_SPEC{
        "PIC16F1765",
        16384,      // program memory (8192 words * 2 bytes/word)
        1024,       // data memory (RAM)
        0,     // EEPROM
        Architecture::PIC16
    };

    static constexpr DeviceSpec PIC16F1768_SPEC{
        "PIC16F1768",
        32768,      // program memory (16384 words * 2 bytes/word)
        2048,       // data memory (RAM)
        256,     // EEPROM
        Architecture::PIC16
    };

    static constexpr DeviceSpec PIC16F1769_SPEC{
        "PIC16F1769",
        32768,      // program memory (16384 words * 2 bytes/word)
        2048,       // data memory (RAM)
        256,     // EEPROM
        Architecture::PIC16
    };

    static constexpr DeviceSpec PIC16F1773_SPEC{
        "PIC16F1773",
        8192,      // program memory (4096 words * 2 bytes/word)
        512,       // data memory (RAM)
        0,     // EEPROM
        Architecture::PIC16
    };

    static constexpr DeviceSpec PIC16F1776_SPEC{
        "PIC16F1776",
        16384,      // program memory (8192 words * 2 bytes/word)
        1024,       // data memory (RAM)
        0,     // EEPROM
        Architecture::PIC16
    };

    static constexpr DeviceSpec PIC16F1777_SPEC{
        "PIC16F1777",
        16384,      // program memory (8192 words * 2 bytes/word)
        1024,       // data memory (RAM)
        0,     // EEPROM
        Architecture::PIC16
    };

    static constexpr DeviceSpec PIC16F1778_SPEC{
        "PIC16F1778",
        32768,      // program memory (16384 words * 2 bytes/word)
        2048,       // data memory (RAM)
        256,     // EEPROM
        Architecture::PIC16
    };

    static constexpr DeviceSpec PIC16F1779_SPEC{
        "PIC16F1779",
        32768,      // program memory (16384 words * 2 bytes/word)
        2048,       // data memory (RAM)
        256,     // EEPROM
        Architecture::PIC16
    };

    static constexpr DeviceSpec PIC16F1782_SPEC{
        "PIC16F1782",
        4096,      // program memory (2048 words * 2 bytes/word)
        128,       // data memory (RAM)
        0,     // EEPROM
        Architecture::PIC16
    };

    static constexpr DeviceSpec PIC16F1783_SPEC{
        "PIC16F1783",
        8192,      // program memory (4096 words * 2 bytes/word)
        256,       // data memory (RAM)
        256,     // EEPROM
        Architecture::PIC16
    };

    static constexpr DeviceSpec PIC16F1784_SPEC{
        "PIC16F1784",
        8192,      // program memory (4096 words * 2 bytes/word)
        256,       // data memory (RAM)
        256,     // EEPROM
        Architecture::PIC16
    };

    static constexpr DeviceSpec PIC16F1786_SPEC{
        "PIC16F1786",
        16384,      // program memory (8192 words * 2 bytes/word)
        1024,       // data memory (RAM)
        256,     // EEPROM
        Architecture::PIC16
    };

    static constexpr DeviceSpec PIC16F1787_SPEC{
        "PIC16F1787",
        16384,      // program memory (8192 words * 2 bytes/word)
        1024,       // data memory (RAM)
        256,     // EEPROM
        Architecture::PIC16
    };

    static constexpr DeviceSpec PIC16F1823_SPEC{
        "PIC16F1823",
        4096,      // program memory (2048 words * 2 bytes/word)
        128,       // data memory (RAM)
        256,     // EEPROM
        Architecture::PIC16
    };

    static constexpr DeviceSpec PIC16F1824_SPEC{
        "PIC16F1824",
        8192,      // program memory (4096 words * 2 bytes/word)
        256,       // data memory (RAM)
        256,     // EEPROM
        Architecture::PIC16
    };

    static constexpr DeviceSpec PIC16F1825_SPEC{
        "PIC16F1825",
        16384,      // program memory (8192 words * 2 bytes/word)
        1024,       // data memory (RAM)
        256,     // EEPROM
        Architecture::PIC16
    };

    static constexpr DeviceSpec PIC16F1826_SPEC{
        "PIC16F1826",
        4096,      // program memory (2048 words * 2 bytes/word)
        128,       // data memory (RAM)
        256,     // EEPROM
        Architecture::PIC16
    };

    static constexpr DeviceSpec PIC16F1827_SPEC{
        "PIC16F1827",
        8192,      // program memory (4096 words * 2 bytes/word)
        256,       // data memory (RAM)
        256,     // EEPROM
        Architecture::PIC16
    };

    static constexpr DeviceSpec PIC16F1828_SPEC{
        "PIC16F1828",
        8192,      // program memory (4096 words * 2 bytes/word)
        256,       // data memory (RAM)
        256,     // EEPROM
        Architecture::PIC16
    };

    static constexpr DeviceSpec PIC16F1829_SPEC{
        "PIC16F1829",
        16384,      // program memory (8192 words * 2 bytes/word)
        1024,       // data memory (RAM)
        256,     // EEPROM
        Architecture::PIC16
    };

    static constexpr DeviceSpec PIC16F1847_SPEC{
        "PIC16F1847",
        16384,      // program memory (8192 words * 2 bytes/word)
        1024,       // data memory (RAM)
        256,     // EEPROM
        Architecture::PIC16
    };

    static constexpr DeviceSpec PIC16F1933_SPEC{
        "PIC16F1933",
        8192,      // program memory (4096 words * 2 bytes/word)
        256,       // data memory (RAM)
        256,     // EEPROM
        Architecture::PIC16
    };

    static constexpr DeviceSpec PIC16F1934_SPEC{
        "PIC16F1934",
        8192,      // program memory (4096 words * 2 bytes/word)
        256,       // data memory (RAM)
        256,     // EEPROM
        Architecture::PIC16
    };

    static constexpr DeviceSpec PIC16F1936_SPEC{
        "PIC16F1936",
        16384,      // program memory (8192 words * 2 bytes/word)
        512,       // data memory (RAM)
        256,     // EEPROM
        Architecture::PIC16
    };

    static constexpr DeviceSpec PIC16F1937_SPEC{
        "PIC16F1937",
        16384,      // program memory (8192 words * 2 bytes/word)
        512,       // data memory (RAM)
        256,     // EEPROM
        Architecture::PIC16
    };

    static constexpr DeviceSpec PIC16F1938_SPEC{
        "PIC16F1938",
        32768,      // program memory (16384 words * 2 bytes/word)
        1024,       // data memory (RAM)
        256,     // EEPROM
        Architecture::PIC16
    };

    static constexpr DeviceSpec PIC16F1939_SPEC{
        "PIC16F1939",
        32768,      // program memory (16384 words * 2 bytes/word)
        1024,       // data memory (RAM)
        256,     // EEPROM
        Architecture::PIC16
    };

    static constexpr DeviceSpec PIC16F1946_SPEC{
        "PIC16F1946",
        16384,      // program memory (8192 words * 2 bytes/word)
        512,       // data memory (RAM)
        256,     // EEPROM
        Architecture::PIC16
    };

    static constexpr DeviceSpec PIC16F1947_SPEC{
        "PIC16F1947",
        32768,      // program memory (16384 words * 2 bytes/word)
        1024,       // data memory (RAM)
        256,     // EEPROM
        Architecture::PIC16
    };

    static constexpr DeviceSpec PIC18F06Q40_SPEC{
        "PIC18F06Q40",
        65536,      // program memory (32768 words * 2 bytes/word)
        4192,       // data memory (RAM)
        512,     // EEPROM
        Architecture::PIC18
    };

    static constexpr DeviceSpec PIC18F06Q41_SPEC{
        "PIC18F06Q41",
        65536,      // program memory (32768 words * 2 bytes/word)
        4192,       // data memory (RAM)
        512,     // EEPROM
        Architecture::PIC18
    };

    static constexpr DeviceSpec PIC18F07Q41_SPEC{
        "PIC18F07Q41",
        131072,      // program memory (65536 words * 2 bytes/word)
        4192,       // data memory (RAM)
        512,     // EEPROM
        Architecture::PIC18
    };

    static constexpr DeviceSpec PIC18F16Q40_SPEC{
        "PIC18F16Q40",
        65536,      // program memory (32768 words * 2 bytes/word)
        4192,       // data memory (RAM)
        512,     // EEPROM
        Architecture::PIC18
    };

    static constexpr DeviceSpec PIC18F16Q41_SPEC{
        "PIC18F16Q41",
        65536,      // program memory (32768 words * 2 bytes/word)
        4192,       // data memory (RAM)
        512,     // EEPROM
        Architecture::PIC18
    };

    static constexpr DeviceSpec PIC18F17Q41_SPEC{
        "PIC18F17Q41",
        131072,      // program memory (65536 words * 2 bytes/word)
        4192,       // data memory (RAM)
        512,     // EEPROM
        Architecture::PIC18
    };

    static constexpr DeviceSpec PIC18F242_SPEC{
        "PIC18F242",
        16384,      // program memory (8192 words * 2 bytes/word)
        512,       // data memory (RAM)
        256,     // EEPROM
        Architecture::PIC18
    };

    static constexpr DeviceSpec PIC18F252_SPEC{
        "PIC18F252",
        32768,      // program memory (16384 words * 2 bytes/word)
        1536,       // data memory (RAM)
        256,     // EEPROM
        Architecture::PIC18
    };

    static constexpr DeviceSpec PIC18F442_SPEC{
        "PIC18F442",
        16384,      // program memory (8192 words * 2 bytes/word)
        512,       // data memory (RAM)
        256,     // EEPROM
        Architecture::PIC18
    };

    static constexpr DeviceSpec PIC18F452_SPEC{
        "PIC18F452",
        32768,      // program memory (16384 words * 2 bytes/word)
        1536,       // data memory (RAM)
        256,     // EEPROM
        Architecture::PIC18
    };

    static constexpr DeviceSpec PIC18F1220_SPEC{
        "PIC18F1220",
        4096,      // program memory (2048 words * 2 bytes/word)
        256,       // data memory (RAM)
        256,     // EEPROM
        Architecture::PIC18
    };

    static constexpr DeviceSpec PIC18F1230_SPEC{
        "PIC18F1230",
        4096,      // program memory (2048 words * 2 bytes/word)
        256,       // data memory (RAM)
        256,     // EEPROM
        Architecture::PIC18
    };

    static constexpr DeviceSpec PIC18F1320_SPEC{
        "PIC18F1320",
        8192,      // program memory (4096 words * 2 bytes/word)
        256,       // data memory (RAM)
        256,     // EEPROM
        Architecture::PIC18
    };

    static constexpr DeviceSpec PIC18F1330_SPEC{
        "PIC18F1330",
        8192,      // program memory (4096 words * 2 bytes/word)
        256,       // data memory (RAM)
        256,     // EEPROM
        Architecture::PIC18
    };

    static constexpr DeviceSpec PIC18F2220_SPEC{
        "PIC18F2220",
        4096,      // program memory (2048 words * 2 bytes/word)
        256,       // data memory (RAM)
        256,     // EEPROM
        Architecture::PIC18
    };

    static constexpr DeviceSpec PIC18F2221_SPEC{
        "PIC18F2221",
        4096,      // program memory (2048 words * 2 bytes/word)
        256,       // data memory (RAM)
        256,     // EEPROM
        Architecture::PIC18
    };

    static constexpr DeviceSpec PIC18F2320_SPEC{
        "PIC18F2320",
        8192,      // program memory (4096 words * 2 bytes/word)
        256,       // data memory (RAM)
        256,     // EEPROM
        Architecture::PIC18
    };

    static constexpr DeviceSpec PIC18F2321_SPEC{
        "PIC18F2321",
        8192,      // program memory (4096 words * 2 bytes/word)
        256,       // data memory (RAM)
        256,     // EEPROM
        Architecture::PIC18
    };

    static constexpr DeviceSpec PIC18F2410_SPEC{
        "PIC18F2410",
        16384,      // program memory (8192 words * 2 bytes/word)
        768,       // data memory (RAM)
        256,     // EEPROM
        Architecture::PIC18
    };

    static constexpr DeviceSpec PIC18F2420_SPEC{
        "PIC18F2420",
        16384,      // program memory (8192 words * 2 bytes/word)
        768,       // data memory (RAM)
        256,     // EEPROM
        Architecture::PIC18
    };

    static constexpr DeviceSpec PIC18F2423_SPEC{
        "PIC18F2423",
        16384,      // program memory (8192 words * 2 bytes/word)
        768,       // data memory (RAM)
        256,     // EEPROM
        Architecture::PIC18
    };

    static constexpr DeviceSpec PIC18F2450_SPEC{
        "PIC18F2450",
        16384,      // program memory (8192 words * 2 bytes/word)
        2048,       // data memory (RAM)
        0,     // EEPROM
        Architecture::PIC18
    };

    static constexpr DeviceSpec PIC18F2455_SPEC{
        "PIC18F2455",
        24576,      // program memory (12288 words * 2 bytes/word)
        2048,       // data memory (RAM)
        256,     // EEPROM
        Architecture::PIC18
    };

    static constexpr DeviceSpec PIC18F2458_SPEC{
        "PIC18F2458",
        24576,      // program memory (12288 words * 2 bytes/word)
        2048,       // data memory (RAM)
        0,     // EEPROM
        Architecture::PIC18
    };

    static constexpr DeviceSpec PIC18F2480_SPEC{
        "PIC18F2480",
        16384,      // program memory (8192 words * 2 bytes/word)
        1536,       // data memory (RAM)
        256,     // EEPROM
        Architecture::PIC18
    };

    static constexpr DeviceSpec PIC18F2510_SPEC{
        "PIC18F2510",
        32768,      // program memory (16384 words * 2 bytes/word)
        1536,       // data memory (RAM)
        0,     // EEPROM
        Architecture::PIC18
    };

    static constexpr DeviceSpec PIC18F2515_SPEC{
        "PIC18F2515",
        49152,      // program memory (24576 words * 2 bytes/word)
        2048,       // data memory (RAM)
        1024,     // EEPROM
        Architecture::PIC18
    };

    static constexpr DeviceSpec PIC18F2520_SPEC{
        "PIC18F2520",
        32768,      // program memory (16384 words * 2 bytes/word)
        1536,       // data memory (RAM)
        256,     // EEPROM
        Architecture::PIC18
    };

    static constexpr DeviceSpec PIC18F2523_SPEC{
        "PIC18F2523",
        32768,      // program memory (16384 words * 2 bytes/word)
        1536,       // data memory (RAM)
        1024,     // EEPROM
        Architecture::PIC18
    };

    static constexpr DeviceSpec PIC18F2525_SPEC{
        "PIC18F2525",
        49152,      // program memory (24576 words * 2 bytes/word)
        2048,       // data memory (RAM)
        1024,     // EEPROM
        Architecture::PIC18
    };

    static constexpr DeviceSpec PIC18F2550_SPEC{
        "PIC18F2550",
        32768,      // program memory (16384 words * 2 bytes/word)
        2048,       // data memory (RAM)
        256,     // EEPROM
        Architecture::PIC18
    };

    static constexpr DeviceSpec PIC18F2553_SPEC{
        "PIC18F2553",
        32768,      // program memory (16384 words * 2 bytes/word)
        2048,       // data memory (RAM)
        256,     // EEPROM
        Architecture::PIC18
    };

    static constexpr DeviceSpec PIC18F2580_SPEC{
        "PIC18F2580",
        32768,      // program memory (16384 words * 2 bytes/word)
        1536,       // data memory (RAM)
        256,     // EEPROM
        Architecture::PIC18
    };

    static constexpr DeviceSpec PIC18F2585_SPEC{
        "PIC18F2585",
        49152,      // program memory (24576 words * 2 bytes/word)
        2048,       // data memory (RAM)
        1024,     // EEPROM
        Architecture::PIC18
    };

    static constexpr DeviceSpec PIC18F2610_SPEC{
        "PIC18F2610",
        65536,      // program memory (32768 words * 2 bytes/word)
        3968,       // data memory (RAM)
        1024,     // EEPROM
        Architecture::PIC18
    };

    static constexpr DeviceSpec PIC18F2620_SPEC{
        "PIC18F2620",
        65536,      // program memory (32768 words * 2 bytes/word)
        3968,       // data memory (RAM)
        1024,     // EEPROM
        Architecture::PIC18
    };

    static constexpr DeviceSpec PIC18F2680_SPEC{
        "PIC18F2680",
        65536,      // program memory (32768 words * 2 bytes/word)
        3968,       // data memory (RAM)
        1024,     // EEPROM
        Architecture::PIC18
    };

    static constexpr DeviceSpec PIC18F4220_SPEC{
        "PIC18F4220",
        4096,      // program memory (2048 words * 2 bytes/word)
        256,       // data memory (RAM)
        256,     // EEPROM
        Architecture::PIC18
    };

    static constexpr DeviceSpec PIC18F4221_SPEC{
        "PIC18F4221",
        4096,      // program memory (2048 words * 2 bytes/word)
        256,       // data memory (RAM)
        256,     // EEPROM
        Architecture::PIC18
    };

    static constexpr DeviceSpec PIC18F4320_SPEC{
        "PIC18F4320",
        8192,      // program memory (4096 words * 2 bytes/word)
        256,       // data memory (RAM)
        256,     // EEPROM
        Architecture::PIC18
    };

    static constexpr DeviceSpec PIC18F4321_SPEC{
        "PIC18F4321",
        8192,      // program memory (4096 words * 2 bytes/word)
        256,       // data memory (RAM)
        256,     // EEPROM
        Architecture::PIC18
    };

    static constexpr DeviceSpec PIC18F4410_SPEC{
        "PIC18F4410",
        16384,      // program memory (8192 words * 2 bytes/word)
        768,       // data memory (RAM)
        256,     // EEPROM
        Architecture::PIC18
    };

    static constexpr DeviceSpec PIC18F4420_SPEC{
        "PIC18F4420",
        16384,      // program memory (8192 words * 2 bytes/word)
        768,       // data memory (RAM)
        256,     // EEPROM
        Architecture::PIC18
    };

    static constexpr DeviceSpec PIC18F4423_SPEC{
        "PIC18F4423",
        16384,      // program memory (8192 words * 2 bytes/word)
        768,       // data memory (RAM)
        256,     // EEPROM
        Architecture::PIC18
    };

    static constexpr DeviceSpec PIC18F4450_SPEC{
        "PIC18F4450",
        16384,      // program memory (8192 words * 2 bytes/word)
        2048,       // data memory (RAM)
        0,     // EEPROM
        Architecture::PIC18
    };

    static constexpr DeviceSpec PIC18F4455_SPEC{
        "PIC18F4455",
        24576,      // program memory (12288 words * 2 bytes/word)
        2048,       // data memory (RAM)
        256,     // EEPROM
        Architecture::PIC18
    };

    static constexpr DeviceSpec PIC18F4458_SPEC{
        "PIC18F4458",
        24576,      // program memory (12288 words * 2 bytes/word)
        2048,       // data memory (RAM)
        0,     // EEPROM
        Architecture::PIC18
    };

    static constexpr DeviceSpec PIC18F4480_SPEC{
        "PIC18F4480",
        16384,      // program memory (8192 words * 2 bytes/word)
        1536,       // data memory (RAM)
        256,     // EEPROM
        Architecture::PIC18
    };

    static constexpr DeviceSpec PIC18F4510_SPEC{
        "PIC18F4510",
        32768,      // program memory (16384 words * 2 bytes/word)
        1536,       // data memory (RAM)
        0,     // EEPROM
        Architecture::PIC18
    };

    static constexpr DeviceSpec PIC18F4515_SPEC{
        "PIC18F4515",
        49152,      // program memory (24576 words * 2 bytes/word)
        2048,       // data memory (RAM)
        1024,     // EEPROM
        Architecture::PIC18
    };

    static constexpr DeviceSpec PIC18F4520_SPEC{
        "PIC18F4520",
        32768,      // program memory (16384 words * 2 bytes/word)
        1536,       // data memory (RAM)
        256,     // EEPROM
        Architecture::PIC18
    };

    static constexpr DeviceSpec PIC18F4523_SPEC{
        "PIC18F4523",
        32768,      // program memory (16384 words * 2 bytes/word)
        1536,       // data memory (RAM)
        1024,     // EEPROM
        Architecture::PIC18
    };

    static constexpr DeviceSpec PIC18F4525_SPEC{
        "PIC18F4525",
        49152,      // program memory (24576 words * 2 bytes/word)
        2048,       // data memory (RAM)
        1024,     // EEPROM
        Architecture::PIC18
    };

    static constexpr DeviceSpec PIC18F4550_SPEC{
        "PIC18F4550",
        32768,      // program memory (16384 words * 2 bytes/word)
        2048,       // data memory (RAM)
        256,     // EEPROM
        Architecture::PIC18
    };

    static constexpr DeviceSpec PIC18F4553_SPEC{
        "PIC18F4553",
        32768,      // program memory (16384 words * 2 bytes/word)
        2048,       // data memory (RAM)
        256,     // EEPROM
        Architecture::PIC18
    };

    static constexpr DeviceSpec PIC18F4580_SPEC{
        "PIC18F4580",
        32768,      // program memory (16384 words * 2 bytes/word)
        1536,       // data memory (RAM)
        256,     // EEPROM
        Architecture::PIC18
    };

    static constexpr DeviceSpec PIC18F4585_SPEC{
        "PIC18F4585",
        49152,      // program memory (24576 words * 2 bytes/word)
        2048,       // data memory (RAM)
        1024,     // EEPROM
        Architecture::PIC18
    };

    static constexpr DeviceSpec PIC18F4610_SPEC{
        "PIC18F4610",
        65536,      // program memory (32768 words * 2 bytes/word)
        3968,       // data memory (RAM)
        1024,     // EEPROM
        Architecture::PIC18
    };

    static constexpr DeviceSpec PIC18F4620_SPEC{
        "PIC18F4620",
        65536,      // program memory (32768 words * 2 bytes/word)
        3968,       // data memory (RAM)
        1024,     // EEPROM
        Architecture::PIC18
    };

    static constexpr DeviceSpec PIC18F4680_SPEC{
        "PIC18F4680",
        65536,      // program memory (32768 words * 2 bytes/word)
        3968,       // data memory (RAM)
        1024,     // EEPROM
        Architecture::PIC18
    };

