// Generated 24/03/2025 GMT

/*
 * Copyright © 2025, Microchip Technology Inc. and its subsidiaries ("Microchip")
 * All rights reserved.
 * 
 * This software is developed by Microchip Technology Inc. and its subsidiaries ("Microchip").
 * 
 * Redistribution and use in source and binary forms, with or without modification, are
 * permitted provided that the following conditions are met:
 * 
 *     1. Redistributions of source code must retain the above copyright notice, this list of
 *        conditions and the following disclaimer.
 * 
 *     2. Redistributions in binary form must reproduce the above copyright notice, this list
 *        of conditions and the following disclaimer in the documentation and/or other
 *        materials provided with the distribution. Publication is not required when
 *        this file is used in an embedded application.
 * 
 *     3. Microchip's name may not be used to endorse or promote products derived from this
 *        software without specific prior written permission.
 * 
 * THIS SOFTWARE IS PROVIDED BY MICROCHIP "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
 * INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL MICROCHIP BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING BUT NOT LIMITED TO
 * PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWSOEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
 * THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

#ifndef _PIC18_CHIP_SELECT_INC_
#define _PIC18_CHIP_SELECT_INC_

#define _HEADER_NOT_FOUND

#ifdef _18F04Q20
#include <pic18f04q20.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F04Q40
#include <pic18f04q40.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F04Q41
#include <pic18f04q41.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F05Q20
#include <pic18f05q20.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F05Q40
#include <pic18f05q40.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F05Q41
#include <pic18f05q41.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F06Q20
#include <pic18f06q20.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F06Q40
#include <pic18f06q40.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F06Q41
#include <pic18f06q41.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F14Q20
#include <pic18f14q20.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F14Q40
#include <pic18f14q40.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F14Q41
#include <pic18f14q41.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F15Q20
#include <pic18f15q20.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F15Q40
#include <pic18f15q40.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F15Q41
#include <pic18f15q41.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F16Q20
#include <pic18f16q20.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F16Q40
#include <pic18f16q40.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F16Q41
#include <pic18f16q41.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F24Q10
#include <pic18f24q10.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F24Q24
#include <pic18f24q24.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F24Q71
#include <pic18f24q71.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F25Q10
#include <pic18f25q10.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F25Q24
#include <pic18f25q24.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F25Q43
#include <pic18f25q43.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F25Q71
#include <pic18f25q71.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F26Q10
#include <pic18f26q10.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F26Q24
#include <pic18f26q24.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F26Q43
#include <pic18f26q43.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F26Q71
#include <pic18f26q71.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F26Q83
#include <pic18f26q83.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F26Q84
#include <pic18f26q84.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F27Q10
#include <pic18f27q10.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F27Q43
#include <pic18f27q43.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F27Q83
#include <pic18f27q83.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F27Q84
#include <pic18f27q84.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F44Q71
#include <pic18f44q71.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F45Q10
#include <pic18f45q10.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F45Q24
#include <pic18f45q24.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F45Q43
#include <pic18f45q43.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F45Q71
#include <pic18f45q71.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F46Q10
#include <pic18f46q10.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F46Q24
#include <pic18f46q24.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F46Q43
#include <pic18f46q43.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F46Q71
#include <pic18f46q71.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F46Q83
#include <pic18f46q83.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F46Q84
#include <pic18f46q84.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F47Q10
#include <pic18f47q10.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F47Q43
#include <pic18f47q43.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F47Q83
#include <pic18f47q83.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F47Q84
#include <pic18f47q84.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F54Q71
#include <pic18f54q71.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F55Q24
#include <pic18f55q24.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F55Q43
#include <pic18f55q43.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F55Q71
#include <pic18f55q71.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F56Q24
#include <pic18f56q24.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F56Q43
#include <pic18f56q43.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F56Q71
#include <pic18f56q71.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F56Q83
#include <pic18f56q83.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F56Q84
#include <pic18f56q84.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F57Q43
#include <pic18f57q43.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F57Q83
#include <pic18f57q83.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _18F57Q84
#include <pic18f57q84.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _TEST_CHIP_
#undef _HEADER_NOT_FOUND
#endif

#ifdef _HEADER_NOT_FOUND
#error Device-specific header could not be found for target chip
#endif

#endif // _PIC18_CHIP_SELECT_INC_
