// Generated 27/03/2025 GMT

/*
 * Copyright © 2025, Microchip Technology Inc. and its subsidiaries ("Microchip")
 * All rights reserved.
 * 
 * This software is developed by Microchip Technology Inc. and its subsidiaries ("Microchip").
 * 
 * Redistribution and use in source and binary forms, with or without modification, are
 * permitted provided that the following conditions are met:
 * 
 *     1. Redistributions of source code must retain the above copyright notice, this list of
 *        conditions and the following disclaimer.
 * 
 *     2. Redistributions in binary form must reproduce the above copyright notice, this list
 *        of conditions and the following disclaimer in the documentation and/or other
 *        materials provided with the distribution. Publication is not required when
 *        this file is used in an embedded application.
 * 
 *     3. Microchip's name may not be used to endorse or promote products derived from this
 *        software without specific prior written permission.
 * 
 * THIS SOFTWARE IS PROVIDED BY MICROCHIP "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
 * INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL MICROCHIP BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING BUT NOT LIMITED TO
 * PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWSOEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
 * THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

#ifndef _PIC_AS_CHIP_SELECT_INC_
#define _PIC_AS_CHIP_SELECT_INC_

#define _HEADER_NOT_FOUND

#ifdef _12F1501
#include <pic12f1501.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _12F1571
#include <pic12f1571.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _12F1572
#include <pic12f1572.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _12F1612
#include <pic12f1612.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _12F1822
#include <pic12f1822.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _12F1840
#include <pic12f1840.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _12LF1501
#include <pic12lf1501.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _12LF1552
#include <pic12lf1552.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _12LF1571
#include <pic12lf1571.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _12LF1572
#include <pic12lf1572.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _12LF1612
#include <pic12lf1612.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _12LF1822
#include <pic12lf1822.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _12LF1840
#include <pic12lf1840.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _12LF1840T39A
#include <pic12lf1840t39a.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _12LF1840T48A
#include <pic12lf1840t48a.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F1454
#include <pic16f1454.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F1455
#include <pic16f1455.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F1459
#include <pic16f1459.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F1503
#include <pic16f1503.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F1507
#include <pic16f1507.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F1508
#include <pic16f1508.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F1509
#include <pic16f1509.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F1512
#include <pic16f1512.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F1513
#include <pic16f1513.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F1516
#include <pic16f1516.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F1517
#include <pic16f1517.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F1518
#include <pic16f1518.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F1519
#include <pic16f1519.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F1526
#include <pic16f1526.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F1527
#include <pic16f1527.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F1574
#include <pic16f1574.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F1575
#include <pic16f1575.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F1578
#include <pic16f1578.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F1579
#include <pic16f1579.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F1613
#include <pic16f1613.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F1614
#include <pic16f1614.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F1615
#include <pic16f1615.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F1618
#include <pic16f1618.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F1619
#include <pic16f1619.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F1703
#include <pic16f1703.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F1704
#include <pic16f1704.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F1705
#include <pic16f1705.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F1707
#include <pic16f1707.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F1708
#include <pic16f1708.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F1709
#include <pic16f1709.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F1713
#include <pic16f1713.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F1716
#include <pic16f1716.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F1717
#include <pic16f1717.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F1718
#include <pic16f1718.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F1719
#include <pic16f1719.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F1764
#include <pic16f1764.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F1765
#include <pic16f1765.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F1768
#include <pic16f1768.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F1769
#include <pic16f1769.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F1773
#include <pic16f1773.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F1776
#include <pic16f1776.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F1777
#include <pic16f1777.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F1778
#include <pic16f1778.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F1779
#include <pic16f1779.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F1782
#include <pic16f1782.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F1783
#include <pic16f1783.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F1784
#include <pic16f1784.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F1786
#include <pic16f1786.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F1787
#include <pic16f1787.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F1788
#include <pic16f1788.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F1789
#include <pic16f1789.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F1823
#include <pic16f1823.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F1824
#include <pic16f1824.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F1825
#include <pic16f1825.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F1826
#include <pic16f1826.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F1827
#include <pic16f1827.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F1828
#include <pic16f1828.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F1829
#include <pic16f1829.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F1829LIN
#include <pic16f1829lin.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F1847
#include <pic16f1847.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F1933
#include <pic16f1933.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F1934
#include <pic16f1934.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F1936
#include <pic16f1936.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F1937
#include <pic16f1937.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F1938
#include <pic16f1938.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F1939
#include <pic16f1939.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F1946
#include <pic16f1946.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16F1947
#include <pic16f1947.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF1454
#include <pic16lf1454.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF1455
#include <pic16lf1455.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF1459
#include <pic16lf1459.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF1503
#include <pic16lf1503.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF1507
#include <pic16lf1507.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF1508
#include <pic16lf1508.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF1509
#include <pic16lf1509.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF1512
#include <pic16lf1512.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF1513
#include <pic16lf1513.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF1516
#include <pic16lf1516.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF1517
#include <pic16lf1517.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF1518
#include <pic16lf1518.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF1519
#include <pic16lf1519.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF1526
#include <pic16lf1526.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF1527
#include <pic16lf1527.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF1554
#include <pic16lf1554.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF1559
#include <pic16lf1559.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF1566
#include <pic16lf1566.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF1567
#include <pic16lf1567.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF1574
#include <pic16lf1574.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF1575
#include <pic16lf1575.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF1578
#include <pic16lf1578.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF1579
#include <pic16lf1579.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF1613
#include <pic16lf1613.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF1614
#include <pic16lf1614.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF1615
#include <pic16lf1615.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF1618
#include <pic16lf1618.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF1619
#include <pic16lf1619.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF1703
#include <pic16lf1703.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF1704
#include <pic16lf1704.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF1705
#include <pic16lf1705.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF1707
#include <pic16lf1707.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF1708
#include <pic16lf1708.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF1709
#include <pic16lf1709.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF1713
#include <pic16lf1713.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF1716
#include <pic16lf1716.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF1717
#include <pic16lf1717.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF1718
#include <pic16lf1718.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF1719
#include <pic16lf1719.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF1764
#include <pic16lf1764.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF1765
#include <pic16lf1765.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF1768
#include <pic16lf1768.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF1769
#include <pic16lf1769.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF1773
#include <pic16lf1773.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF1776
#include <pic16lf1776.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF1777
#include <pic16lf1777.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF1778
#include <pic16lf1778.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF1779
#include <pic16lf1779.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF1782
#include <pic16lf1782.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF1783
#include <pic16lf1783.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF1784
#include <pic16lf1784.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF1786
#include <pic16lf1786.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF1787
#include <pic16lf1787.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF1788
#include <pic16lf1788.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF1789
#include <pic16lf1789.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF1823
#include <pic16lf1823.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF1824
#include <pic16lf1824.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF1824T39A
#include <pic16lf1824t39a.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF1825
#include <pic16lf1825.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF1826
#include <pic16lf1826.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF1827
#include <pic16lf1827.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF1828
#include <pic16lf1828.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF1829
#include <pic16lf1829.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF1847
#include <pic16lf1847.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF1902
#include <pic16lf1902.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF1903
#include <pic16lf1903.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF1904
#include <pic16lf1904.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF1906
#include <pic16lf1906.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF1907
#include <pic16lf1907.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF1933
#include <pic16lf1933.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF1934
#include <pic16lf1934.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF1936
#include <pic16lf1936.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF1937
#include <pic16lf1937.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF1938
#include <pic16lf1938.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF1939
#include <pic16lf1939.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF1946
#include <pic16lf1946.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _16LF1947
#include <pic16lf1947.inc>
#undef _HEADER_NOT_FOUND
#endif

#ifdef _TEST_CHIP_
#undef _HEADER_NOT_FOUND
#endif

#ifdef _HEADER_NOT_FOUND
#error Device-specific header could not be found for target chip
#endif

#endif // _PIC_AS_CHIP_SELECT_INC_
